name: build-win

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows:
    name: Build for Windows (x86_64)
    runs-on: windows-2025
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build samloader
        run: |
          rustup update
          cargo build -p samloader --release
          VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "samloader") | .version')
          cd target/release
          7z a ../../samloader-v$VERSION-windows-x86_64.zip samloader.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: samloader-*.zip
          archive: false
